#!/bin/bash

set -e

#Completely deletion of the apt-btrfs-snapshot dpkg hook to only use kaisen-timeshift-apt instead of it
if [ "$1" = "configure" ]; then
	#Fix bug with the systemd still uses fstab
	if command -v apt-btrfs-snapshot > /dev/null; then echo "#" >> /etc/fstab && sed -i '$d' /etc/fstab && systemctl daemon-reload
	#No running update-grub when apt-snapshot subvolumes will be delete
	sed -i 's/os.system("update-grub")//g' /usr/bin/apt-btrfs-snapshot
	#Deletion of all snapshot taken by apt-btrfs-snapshot
	for delete in $(btrfs subvolume list / | grep @apt-snapshot | grep -v @apt-snapshot-old-root | awk '{ print $9 }'); do apt-btrfs-snapshot delete $delete; done
	#Remove the hook dpkg file to disable apt-btrfs-snapshot
        rm -f /etc/apt/apt.conf.d/9999btrfs-snapshot
	fi
fi
